### ISSUE TITLE
[Bug] CSS-Grid "grid-template-columns" für Desktop viewport auf 2fr 1fr anpassen

### ISSUE THREAD

**Issue by oliveratgithub** [zorgch/zorg-code#9]
![zorg v4_0_0 responsive - grid-columns sizes](https://user-images.githubusercontent.com/280207/68152465-021fac80-ff44-11e9-9db7-963f217751eb.png)

https://github.com/zorgch/zorg-code/blob/b17f749fa9018e398ed588346177d48a503d6601/www/css/css.php#L124

**Comment by oliveratgithub** [comment]
@fbentele bi nöd sicher ob min vorgschlagene Change sinnvoll & richtig isch… Wa meinsch du dezue?

**Comment by fbentele** [comment]
als 2fr 1fr macht sicher sinn, aber im commit https://github.com/zorgch/zorg-code/commit/b2f05528f65afd534a6c69012cdfcd15f7515599 isch nomol was anders, döte wöri das nöd uf body > * mache sondern nur uf die chind wo würkli betroffe sind.

**Comment by oliveratgithub** [comment]
@fbentele merci, passi demfall nomel a
